[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "edgar-sec"
version = "2.0.1"
description = "A feature-rich python package for interacting with the US Securities and Exchange Commission API: EDGAR"
authors = [
    "Nikhil Sunder <nsunder724@gmail.com>",
    "John Bernardin <jbbernardin725@gmail.com>",
    "Jake Schultz",
    "Rayhan Rahman",
]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/edgar-sec-dev-team/edgar-sec"
documentation = "https://edgar-sec-dev-team.github.io/edgar-sec/"
packages = [{include = "edgar_sec", from = "src"}]
include = ["src/edgar_sec/py.typed"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Office/Business :: Financial :: Investment"
]
keywords = [
    "edgar", "sec", "api", "finance", "reporting", "economics", "investing",
    "python", "data", "financial-data", "us-securities-and-exchange-commission",
    "cache", "financial analysis", "economic analysis", "data analysis",
    "data science", "data visualization", "data mining", "data wrangling", "data cleaning"
]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
httpx = "*"
tenacity = "*"
cachetools = "*"
asyncache = "*"

[tool.poetry.group.dev.dependencies]
types-cachetools = "*"
pytest = "*"
pytest-cov = "*"
pylint = "*"
mypy = "*"
bandit = "*"
pip-audit = "*"
pre-commit = "*"
hypothesis = "*"
sphinx = "*"
pydata-sphinx-theme = "*"
sphinx-design = "*"
sphinx-autodoc-typehints = "*"
myst-parser = "*"
linkify-it-py = "* "
sphinxcontrib-googleanalytics = "*"
tox = "*"
pytest-asyncio = "*"
pytest-mock = "*"
tomli = "*"
sphinx-sitemap = "*"
sphinxext-opengraph = "*"
matplotlib = "*"
toml = "*"

[tool.poetry.extras]
types = ["types-cachetools"]

[tool.mypy]
files = "edgar_sec"
ignore_missing_imports = true

[tool.pylint]
max-line-length = 200
disable = ["C0415", "C2801", "C0114", "C0115", "C0116", "C0302", "C0301", "E0401", "R0902", "R0913", "R0917", "R0914", "R0912", "R0904", "R1705", "C0103", "R1710"]
ignore-patterns = [".*\\.pyi$"]

[tool.bandit]
exclude_dirs = ["tests", "docs"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "src"
